<?php

/**
 * @file
 * Contains wm_embed_slideshow.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wm_embed_slideshow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wm_embed_slideshow module.
    case 'help.page.wm_embed_slideshow':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates an embed slideshow gallery button for the ckeditor.') . '</p>';
      return $output;

    default:
  }
}
